### ISSUE TITLE
"cru not found" issue

### ISSUE THREAD

**Issue by devisdevis** [ictp-esp/RegCM#8]
Hello,

I am trying to install this version of RegCM and could not complete the installation on ubuntu.
I get this error when I run the "make":

_make  all-recursive
make[1]: Entering directory '/home/---REGCM/RegCM'
Making all in external
make[2]: Entering directory '/home/---/REGCM/RegCM/external'
rm -f libaerosol.a
cru libaerosol.a mo_simple_plumes.o 
/bin/bash: line 1: cru: command not found
make[2]: *** [Makefile:363: libaerosol.a] Error 127
make[2]: Leaving directory '/home/---/REGCM/RegCM/external'
make[1]: *** [Makefile:398: all-recursive] Error 1
make[1]: Leaving directory '/home/---/REGCM/RegCM'
make: *** [Makefile:339: all] Error 2_

I had already run the "autoreconf" and the "./configure"

Any help?? Thank you

**Comment by graziano-giuliani** [comment]
It is the ar program which is missing from the system. Is the binutils package installed?

dpkg -S /usr/bin/ar
binutils: /usr/bin/ar

I suggest installing the build-essential package, which should install all the missing bits.

**Comment by devisdevis** [comment]
Dear Giuliani,

I have the build-essential package installed already, and the ar is installed (see the terminal screenshot). 
I even tried "AR=ar" before the make, but the error persists.

![image](https://user-images.githubusercontent.com/20596326/121950726-87d32300-cd49-11eb-8612-caeb7162edac.png)

Thank you

**Comment by devisdevis** [comment]
When I use the RegCM-4.7.1 another error pops up.

![image](https://user-images.githubusercontent.com/20596326/121952452-c4a01980-cd4b-11eb-8130-47baea019b6a.png)

**Comment by graziano-giuliani** [comment]
Was the binutil installed before the configure stage? If not, the configure script would not have detected the ar program. Running the configure step on ubuntu I have a line like this one:
[....]
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar                                                                             <<<<<------ This one
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
[....]
For the second error, can you please post the gfortran version:

gfortran --version

**Comment by devisdevis** [comment]
Thank you, Giuliani,
The ar issue is solved. I needed to install the binutils (I thought it was part of the build-essential) and the libtool.
But the same error I got in running the RegCM-4.7.1 is stopping the "make" process now. 

----------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/20596326/122032354-15048f00-cdbf-11eb-83b3-80765cef480e.png)

--------------------------------------------------------------------------------------------------------------
I read it is a Fortran version issue but not sure ...
My gfortran version on pop os (ubuntu derivated) is: 
**GNU Fortran (Ubuntu 10.3.0-1ubuntu1) 10.3.0**

Thank you

**Comment by graziano-giuliani** [comment]
Ach... new gffortran, new flags.

Can you please try modifying configure.ac file:
diff --git a/configure.ac b/configure.ac
index 8161fdb8..18f3c475 100644
--- a/configure.ac
+++ b/configure.ac
@@ -437,7 +437,7 @@ if test -z "$COMPILER_GNU_TRUE"; then
 #      exit 1
 #    fi
 #  fi
-  FCFLAGS="-fconvert=big-endian -fno-range-check -fPIC"
+  FCFLAGS="-fallow-invalid-boz -fconvert=big-endian -fno-range-check -fPIC"
   OMPFLAGS="-fopenmp"
   CPRDEF="GNU"
   AC_SUBST(FCFLAGS)

**Comment by devisdevis** [comment]
Top, @graziano-giuliani  :+1:
thank you very much, it works
Many thanks

**Comment by sh-iz** [comment]
I've tried everything but I'm still facing an issue stating " /bin/bash: cru: command not found "
What am I supposed to do?

ps. I've installed binutils too.

<img width="305" alt="Screenshot 2021-06-20 151921" src="https://user-images.githubusercontent.com/67411772/122669438-f47f6f00-d1da-11eb-9323-c9cc0d7f5a1b.png">

**Comment by devisdevis** [comment]
@sh-iz,
Please check if you have these two packages
`sudo apt install binutils build-essential `

**Comment by sh-iz** [comment]
> @sh-iz,
> Please check if you have these two packages
> `sudo apt install binutils build-essential `

sorry but it still doesn't work. 
The packages were already installed for me.
I don't get whats the issue
